---
# This playbook will create a Docker UCP environment

- include: playbooks/create_vms.yml
- include: playbooks/power_on_guests.yml
- include: playbooks/config_networking.yml
- include: playbooks/distribute_keys.yml
- include: playbooks/install_haproxy.yml
- include: playbooks/install_ntp.yml
- include: playbooks/install_docker.yml
- include: playbooks/config_lvs.yml
- include: playbooks/start_docker.yml
- include: playbooks/docker_post_config.yml
- include: playbooks/install_nfs_server.yml
- include: playbooks/install_nfs_clients.yml
- include: playbooks/install_ucp_nodes.yml
- include: playbooks/install_dtr_nodes.yml
- include: playbooks/install_worker_nodes.yml
